name: (test2) A Docker-based GitHub Action driver
# プライベートアクション版

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: test2-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test2:
    name: A Docker-based GitHub Action driver
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ./ # なんか変だけどまちがってない
        id: hello
        with:
          who-to-greet: "Mona the Octocat"
      # Use the output from the `hello` step
      - name: Get the output time
        env:
          OUTPUT_TIME: ${{ steps.hello.outputs.time }}
        run: echo "The time was \"$OUTPUT_TIME\""
